export const FETCH_START = 'FETCH_START'
export const FETCH_TOOL_USER_SUCCESS = 'FETCH_TOOL_USER_SUCCESS'
export const FETCH_ERROR = 'FETCH_ERROR'
export const ADD_NEW_TOOL_USER_ROW = 'ADD_NEW_TOOL_USER_ROW'

export const FETCH_TOOL_SUCCESS = 'FETCH_TOOL_SUCCESS'

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
